-- Generated from generator/demo_specs/aws-vietnam-aquaculture-traceability.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-aquaculture-traceability
-- This is the schema that is actually deployed for VIETNAM_AQUACULTURE_TRACEABILITY.

-- Alerts fire on the bottom tail of Traceability Coverage
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_TRACEABILITY_COVERAGE) AS T
  FROM RAW.METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_TRACEABILITY_COVERAGE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_TRACEABILITY_COVERAGE), 2) AS AVG_TRACEABILITY_COVERAGE,
  ROUND(AVG(f.KPI_HARVEST_TO_EXPORT), 2) AS AVG_HARVEST_TO_EXPORT,
  ROUND(AVG(f.KPI_QR_CODE_SCANS_DAY), 2) AS AVG_QR_CODE_SCANS_DAY,
  ROUND(AVG(f.KPI_FARM_TO_PLATE_TIME), 2) AS AVG_FARM_TO_PLATE_TIME,
  ROUND(AVG(f.KPI_DATA_COMPLETENESS), 2) AS AVG_DATA_COMPLETENESS
FROM RAW.METRICS f
JOIN RAW.DOCUMENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_TRACEABILITY_COVERAGE), 2) AS AVG_TRACEABILITY_COVERAGE,
  ROUND(AVG(f.KPI_HARVEST_TO_EXPORT), 2) AS AVG_HARVEST_TO_EXPORT,
  ROUND(AVG(f.KPI_QR_CODE_SCANS_DAY), 2) AS AVG_QR_CODE_SCANS_DAY,
  ROUND(AVG(f.KPI_FARM_TO_PLATE_TIME), 2) AS AVG_FARM_TO_PLATE_TIME,
  ROUND(AVG(f.KPI_DATA_COMPLETENESS), 2) AS AVG_DATA_COMPLETENESS
FROM RAW.METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_TRACEABILITY_COVERAGE) AS KPI_TRACEABILITY_COVERAGE, AVG(KPI_HARVEST_TO_EXPORT) AS KPI_HARVEST_TO_EXPORT, AVG(KPI_QR_CODE_SCANS_DAY) AS KPI_QR_CODE_SCANS_DAY, AVG(KPI_FARM_TO_PLATE_TIME) AS KPI_FARM_TO_PLATE_TIME, AVG(KPI_DATA_COMPLETENESS) AS KPI_DATA_COMPLETENESS FROM RAW.METRICS),
     en AS (SELECT SUM(KPI_BATCHES_TRACKED) AS KPI_BATCHES_TRACKED, SUM(KPI_CERTIFIED_FARMS) AS KPI_CERTIFIED_FARMS FROM RAW.DOCUMENTS)
  SELECT 1 AS SORT_ORDER, 'Traceability Coverage' AS TITLE, KPI_TRACEABILITY_COVERAGE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TRACEABILITY_COVERAGE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Batches Tracked' AS TITLE, KPI_BATCHES_TRACKED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_BATCHES_TRACKED) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Harvest-to-Export' AS TITLE, KPI_HARVEST_TO_EXPORT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_HARVEST_TO_EXPORT), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Certified Farms' AS TITLE, KPI_CERTIFIED_FARMS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_CERTIFIED_FARMS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'QR-Code Scans/Day' AS TITLE, KPI_QR_CODE_SCANS_DAY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_QR_CODE_SCANS_DAY) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Farm-to-Plate Time' AS TITLE, KPI_FARM_TO_PLATE_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FARM_TO_PLATE_TIME), 1) AS DECIMAL(38,1))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Data Completeness' AS TITLE, KPI_DATA_COMPLETENESS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DATA_COMPLETENESS)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
